# Generated by Django 3.2.2 on 2021-05-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default='모름', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(default='모름', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(default='모름', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='memo',
            field=models.TextField(default='메모 없음'),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.CharField(default='모름', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default='모름', max_length=255),
        ),
    ]
