# Generated by Django 3.2.2 on 2021-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateApp', '0002_auto_20210512_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('memo', models.TextField(default='메모 없음')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
