# Generated by Django 3.2.1 on 2021-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
    ]
