# Generated by Django 3.2.1 on 2021-05-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='memo',
            field=models.TextField(default='no memo'),
        ),
    ]
