# Generated by Django 3.2.1 on 2021-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0003_auto_20210505_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(default='몰라', max_length=255),
        ),
    ]
