# Generated by Django 3.2.1 on 2021-05-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageApp', '0004_post_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.CharField(max_length=255),
        ),
    ]
